### ISSUE TITLE
What to do when live stream is finished?

### ISSUE THREAD

**Issue by bigtunacan** [WatchPeopleCode/WatchPeopleCode#31]
Do I need to do anything when I'm done broadcasting my live stream?

**Comment by eleweek** [comment]
No, everything should work automatically. Please let us know if you have(or had) any issue.

**Comment by bigtunacan** [comment]
Ok; so I notice it did switch to `Finished` at some point, so I was likely looking too quickly.  However; I have noticed that some will say `Recording Available` after they are finished.  It appears these are all YouTube vids.  I stream and archive on Twitch, but then it does not show `Recording Available` for Twitch.

**Comment by eleweek** [comment]
Yeah, there is a bit of delay with setting flairs, typically a couple of minutes. 

As for Recording Available on twitch, you can leave a commend containing "Recording available" or "Recording is available" and it will set your flair to "Recording Available"(instead of "Finished"). 

BTW, consider uploading your recordings on youtube, since twitch auto-deletes old recordings(after 2 weeks).

**Comment by bigtunacan** [comment]
@eleweek Thanks for the help.  I'll update my comments in the future; wasn't clear how that worked.

I save all of my streams locally as I'm broadcasting as well as doing the temporary archiving on Twitch.  Then I can selectively upload to YouTube if I think the stream was worthwhile.

**Comment by eleweek** [comment]
> Thanks for the help

You're welcome!
