### ISSUE TITLE
Why not use blueprint?

### ISSUE THREAD

**Issue by arthurbarros** [WatchPeopleCode/WatchPeopleCode#5]
Is there any (architecture) reason why not use flask-blueprint ? Your app seems pretty large.

Would love to discuss more about it.
Thanks in advance

**Comment by elimohl** [comment]
What are the reasons to use it right now?

**Comment by arthurbarros** [comment]
In my opnion, because of this:
- code organization - the easiest to understand the structure of a large app, more attention you will get from the community.
- decoupling - split the responaabilidade of views (controllers) and models, making the responsability of each simple to understand.

**Comment by eleweek** [comment]
Well, in principle, we agree, blueprints are a good thing. But right now there is no advantage for blueprints. Maybe in a couple of weeks we'll add them, so I am going to leave this open.

**Comment by paked** [comment]
Just gonna throw my opinion into this...
I think blueprints should be implemented into the code as soon as the current refractor is over, I've spent a bit of time reading over the code and anything to increase structure and readability should be done soon. There are a lot of people who want to contribute but can't due to the (lack of) organization and documentation, however this might be an entirely separate issue entirely..

**Comment by arthurbarros** [comment]
@paked +1

**Comment by eleweek** [comment]
Code complexity and using blueprints are two different things. Flask-related code isn't complicated at all. C'mon a few views + a few models + one form -- how splitting these in three different files would help? 

The code that deals with api is complicated, but this is because dealing with 3 kinds of API isn't straightforward. Some refactoring is definitely needed though. 

As for documentation, pull requests with documentations will be gladly accepted.

**Comment by arthurbarros** [comment]
@eleweek totally agree in that point of Blueprints and complexity been different things.
But the benefits about "splitting in more views, models and form" is about Single Responsibility Principle, if we are able to split the project into modules, and this modules has a clear responsibility, then everything would be more easy,  maintenance and testing.

Thats is just my two cents

**Comment by eleweek** [comment]
@arthurbarros We split the app into smaller files today, so I'm closing this. For I agree with your point, but I still tend to keep things simple/in one file until project gets big enough.
